export default {
  title: 'Avengers Infinity War (2018)',
  filename: '/movies/Avengers Infinity War (2019)/Avengers Infinity War (2018).mkv',
  tracks: [
    {
      title: '',
      language: '',
      number: 0,
      newNumber: 0,
      trackType: 'video',
      codecType: 'MPEG-H/HEVC/H.265',
      isDefault: false,
      isEnabled: false,
      isForced: false,
      isMuxed: true,
    },
    {
      title: 'Main Track',
      language: 'eng',
      number: 1,
      newNumber: 1,
      trackType: 'audio',
      codecType: 'TrueHD Atmos',
      isDefault: true,
      isEnabled: true,
      isForced: false,
      isMuxed: true,
      audioChannels: 8,
      bps: undefined,
    },
    {
      title: 'English',
      language: 'eng',
      number: 2,
      newNumber: 2,
      trackType: 'audio',
      codecType: 'AC-3',
      isDefault: false,
      isEnabled: true,
      isForced: false,
      isMuxed: true,
      audioChannels: 6,
      bps: undefined,
    },
    {
      title:
        'English / DTS-HD Master Audio / 7.1 / 48 kHz / 4 419 kbps / 24-bit (DTS Core: 5.1 / 48 kHz / 1509 kbps / 24-bit)',
      language: 'eng',
      number: 3,
      newNumber: 3,
      trackType: 'audio',
      codecType: 'DTS-HD Master Audio',
      isDefault: false,
      isEnabled: true,
      isForced: false,
      isMuxed: true,
      audioChannels: 8,
      bps: undefined,
    },
    {
      title: 'English (SDH)',
      language: 'eng',
      number: 4,
      newNumber: 4,
      trackType: 'subtitles',
      codecType: 'HDMV PGS',
      isDefault: false,
      isEnabled: true,
      isForced: false,
      isMuxed: true,
    },
    {
      title: 'French',
      language: 'fre',
      number: 5,
      newNumber: 5,
      trackType: 'subtitles',
      codecType: 'HDMV PGS',
      isDefault: false,
      isEnabled: true,
      isForced: false,
      isMuxed: true,
    },
    {
      title: 'Spanish',
      language: 'spa',
      number: 6,
      newNumber: 6,
      trackType: 'subtitles',
      codecType: 'HDMV PGS',
      isDefault: false,
      isEnabled: true,
      isForced: false,
      isMuxed: true,
    },
  ],
  dir: '/movies/Avengers Infinity War (2018)',
  files: [
    'Avengers Infinity War (2018).nfo',
    'Avengers Infinity War (2018)-poster.jpg',
    'Avengers Infinity War (2018)-fanart.jpg',
    'Avengers Infinity War (2018).mkv',
  ],
  poster: 'Avengers Infinity War (2018)-poster.jpg',
  fanart: 'Avengers Infinity War (2018)-fanart.jpg',
  nfo: 'Avengers Infinity War (2018).nfo',
  videoTag: 'MPEG-H/HEVC/H.265',
  audioTag: 'TrueHD Atmos 8ch',
}
